services:
  database:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT}:11434"
    restart: always
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: ./
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      database:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL=${OLLAMA_CHAT_MODEL}
      - SPRING_AI_OLLAMA_CHAT_OPTIONS_TEMPERATURE=${OLLAMA_CHAT_TEMPERATURE}
      - SPRING_AI_OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL}
      - SERVER_ERROR_INCLUDE_MESSAGE=always
      - SERVER_ERROR_INCLUDE_BINDING_ERRORS=always
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}

volumes:
  postgres_data:
  ollama_data: