spring:
  application:
    name: movierecommender

  datasource:
    url: jdbc:postgresql://localhost:5432/movierecommender_database
    username: movierecommender_database_username
    password: movierecommender_database_password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta.persistence.validation.mode: none
    hibernate:
      ddl-auto: update
    show-sql: false

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
      chat:
        options:
          model: llama3.1:8b
          temperature: 0.7

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret-key: RHcPLpkGDZ6WVq4LvGpqLhC9Rb6c5b17
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

cors:
  allowed-origins: http://localhost:5173

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: false