package com.torm.movierecommender.exception;

public enum ErrorCode {
    UNKNOWN_ERROR,
    INTERNAL_SERVER_ERROR,
    ARGUMENT_INVALID_ERROR,
    TITLE_BLANK_ERROR,
    TITLE_MAX_SIZE_ERROR,
    RELEASE_YEAR_NULL_ERROR,
    RELEASE_YEAR_MIN_ERROR,
    RELEASE_YEAR_MAX_ERROR,
    DIRECTORS_EMPTY_ERROR,
    DIRECTORS_ITEMS_BLANK_ERROR,
    DIRECTORS_MAX_SIZE_ERROR,
    GENRES_EMPTY_ERROR,
    GENRES_ITEMS_BLANK_ERROR,
    GENRES_ITEMS_INVALID_ERROR,
    PLOT_BLANK_ERROR,
    PLOT_MAX_SIZE_ERROR,
    IDENTIFIER_BLANK_ERROR,
    IDENTIFIER_MAX_SIZE_ERROR,
    PASSWORD_BLANK_ERROR,
    PASSWORD_MAX_SIZE_ERROR,
    REFRESH_TOKEN_BLANK_ERROR,
    RATING_NULL_ERROR,
    RATING_MIN_ERROR,
    RATING_MAX_ERROR,
    EXCLUDED_GENRES_ITEMS_BLANK_ERROR,
    EXCLUDED_GENRES_ITEMS_INVALID_ERROR,
    MIN_RELEASE_YEAR_MIN_ERROR,
    MIN_RELEASE_YEAR_MAX_ERROR,
    USERNAME_BLANK_ERROR,
    USERNAME_MIN_SIZE_ERROR,
    USERNAME_MAX_SIZE_ERROR,
    USERNAME_INVALID_ERROR,
    EMAIL_BLANK_ERROR,
    EMAIL_MIN_SIZE_ERROR,
    EMAIL_MAX_SIZE_ERROR,
    EMAIL_INVALID_ERROR,
    PASSWORD_MIN_SIZE_ERROR,
    PASSWORD_PATTERN_1_ERROR,
    PASSWORD_PATTERN_2_ERROR,
    PASSWORD_PATTERN_3_ERROR,
    PASSWORD_PATTERN_4_ERROR,
    PASSWORD_PATTERN_5_ERROR,
    USER_UNAUTHORIZED_ERROR,
    MOVIE_ID_POSITIVE_ERROR,
    MOVIE_CONFLICT_ERROR,
    CREDENTIALS_INVALID_ERROR,
    MOVIE_NOT_FOUND_ERROR,
    REFRESH_TOKEN_INVALID_ERROR,
    USERNAME_CONFLICT_ERROR,
    EMAIL_CONFLICT_ERROR,
    MOVIE_ID_NULL_ERROR,
    MOVIE_ID_MIN_ERROR;

    public static ErrorCode fromString(String errorCode) {
        if (errorCode == null || errorCode.isBlank())
            return UNKNOWN_ERROR;

        try {
            return ErrorCode.valueOf(errorCode);
        } catch (IllegalArgumentException e) {
            return UNKNOWN_ERROR;
        }
    }
}